version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000" 
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"  

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80" 
